### PR TITLE
Upgrade the netteForms.js to the Nette 3.0 version

### PR DESCRIPTION
**Pull request by jaroslavlibal**
The current master does not fully support Nette 3.

- Replaced the included netteForms.js with its current version and applied the same modifications to it.
- Replaced Nette.addEvent(el) with the el.addEventListener() calls.

### CODE REVIEW

**Comment by jaroslavlibal** [comment]
Is there anything I can do to get this into some release? As I'm not an adept at javascript, I haven't done any larger refactoring. Just replaced the included forms.js with a new version and provided the same modifications like the original author did in the master branch + replaced listener calls.

**Comment by petrparolek** [comment]
In my case PR doesn't work and I don't know how fix it. Error message isn't shown bellow item

**Comment by radimvaculik** [comment]
Already done @ https://github.com/contributte/live-form-validation/commit/eb847873eb3483c73382fdbd961b7c2e9dd08365 🚀

**Comment by jaroslavlibal** [comment]
Great, I'm glad that the upgrade is finally in the master, but at the same time I'm a little disappointed that I wasted my time.

I asked what else is needed to be done (here and also on slack), I declared that it works for us in production, I did three upgrades to the latest nette.forms.js version hoping it will be merge soon... and I don't know what I did wrong that my version had to remain unmegerd over a year and forever.

**Comment by f3l1x** [comment]
Hey @jaroslavlibal, I am very thankful what have you done here. From my point of view it wasn't waste of time, merged version is based on your work, so you should be proud. @dakorpar is one of stable contributte's member. There is a direct line beetween me and him, so I picked his version and deals with details. 

Please, don't be sad, you have done a excellent job here. I am looking for your another contributtion.

**Pull request closed without merging**
